using System.Collections;
using UnityEngine;
using UnityEngine.SceneManagement;

public class PlayerDeath : MonoBehaviour
{
    public AudioSource audioSource;
    public AudioClip deathSound;

    public SpriteRenderer sprite;
    public float blinkInterval = 0.1f;
    public int blinkCount = 6;

    bool isDead = false;

    private void OnCollisionEnter2D(Collision2D collision)
    {
        if (isDead) return;

        if (collision.collider.CompareTag("wall"))
        {
            StartCoroutine(Die());
        }
    }

    IEnumerator Die()
    {
        isDead = true;

        // ðŸ”Š ØµÙˆØª Ø§Ù„Ù…ÙˆØª
        if (audioSource && deathSound)
            audioSource.PlayOneShot(deathSound);

        // âœ¨ ÙˆÙ…ÙŠØ¶
        for (int i = 0; i < blinkCount; i++)
        {
            sprite.enabled = false;
            yield return new WaitForSeconds(blinkInterval);
            sprite.enabled = true;
            yield return new WaitForSeconds(blinkInterval);
        }

        // ðŸ”„ Ø±ÙŠØ³ØªØ§Ø±Øª
        SceneManager.LoadScene(SceneManager.GetActiveScene().name);
    }
}
